# Generated by Django 2.0.7 on 2018-08-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c87_ivr_187',
            fields=[
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('INTERV_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('COD_FISC_P_IVA', models.CharField(max_length=16)),
                ('NUM_TEL', models.CharField(max_length=15)),
                ('POST_SELECTION', models.CharField(max_length=15)),
                ('NOME', models.CharField(max_length=100)),
                ('DATA_INT', models.CharField(max_length=10)),
                ('MACRO_ESIGENZA', models.CharField(max_length=15)),
                ('ORA', models.CharField(max_length=5)),
                ('ASC', models.CharField(max_length=20)),
                ('MODULO', models.CharField(max_length=20)),
                ('SEGMENTO', models.CharField(max_length=15)),
                ('QQ0', models.IntegerField()),
                ('DD1', models.IntegerField()),
                ('DD2', models.IntegerField()),
                ('DD3', models.IntegerField()),
                ('DD4', models.IntegerField()),
                ('DD5', models.IntegerField()),
                ('DD6', models.IntegerField()),
                ('DD7', models.IntegerField()),
                ('DD8', models.IntegerField()),
            ],
        ),
    ]
