# Generated by Django 2.0.7 on 2018-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0002_auto_20181114_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkt_money_value',
            name='sortorder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
