# Generated by Django 2.0.7 on 2018-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0003_tkt_money_value_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tkt_money_value',
            name='discounted',
            field=models.CharField(default='S', max_length=1),
            preserve_default=False,
        ),
    ]
