# Generated by Django 2.0.7 on 2018-11-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0004_tkt_money_value_discounted'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_number_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='discount_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='discount_tracker',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='CED.discount_type'),
        ),
        migrations.AddField(
            model_name='discount_tracker',
            name='value_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='CED.discount_number_type'),
        ),
    ]
