# Generated by Django 2.0.7 on 2018-11-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0005_auto_20181122_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='tkt_discount_association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_order', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CED.discount_tracker')),
                ('tkt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CED.tkt_money_value')),
            ],
        ),
    ]
