# Generated by Django 2.0.7 on 2018-11-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0006_tkt_discount_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_tracker',
            name='order',
        ),
    ]
