# Generated by Django 2.0.7 on 2018-11-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CED', '0007_remove_discount_tracker_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount_tracker',
            old_name='value',
            new_name='disc_value',
        ),
    ]
