from django.db import models


class month_tr(models.Model):
    name = models.CharField(max_length=20, primary_key=True, unique=True)
    number = models.CharField(max_length=2)
    initials = models.CharField(max_length=4)
    days = models.IntegerField()

class days_tr(models.Model):
    name = models.CharField(max_length=20, primary_key=True, unique=True)
    isonumber = models.IntegerField()
    number = models.IntegerField()
    initials = models.CharField(max_length=3)

class festivity_tr(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    name = models.CharField(max_length=50, unique=True)
    day = models.IntegerField()
    monthname = models.ForeignKey(month_tr, on_delete=models.PROTECT)

class db_update_tracker(models.Model):
    db_name = models.CharField(max_length=20)
    date_hour = models.CharField(max_length=16)

class sites_tracker(models.Model):
    sitename = models.CharField(max_length=10)
    manager = models.CharField(max_length=50)
    fromdate = models.DateField(default="1970-01-01")
    todate = models.DateField(default="2099-12-31")
    def __str__(self):
        return self.sitename

class order_tracker(models.Model):
    pafdesc = models.CharField(max_length=10)
    description = models.CharField(max_length=100)
    site = models.ForeignKey(sites_tracker, on_delete=models.PROTECT)
    def __str__(self):
        return self.pafdesc

class supervisor_tracker(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    order = models.ForeignKey(order_tracker, on_delete=models.PROTECT)
    site = models.ForeignKey(sites_tracker, on_delete=models.PROTECT)
    fromdate = models.DateField(default="1970-01-01")
    todate = models.DateField(default="2099-12-31")
    def __str__(self):
        return self.surname

class contract_tracker(models.Model):
    name = models.CharField(max_length=10)
    order = models.ForeignKey(order_tracker, on_delete=models.PROTECT)
    fromdate = models.DateField(default="1970-01-01")
    todate = models.DateField(default="2099-12-31")
    def __str__(self):
        return self.name

class discount_type(models.Model):
    description = models.CharField(max_length=100)

class discount_number_type(models.Model):
    description = models.CharField(max_length=100)

class discount_tracker(models.Model):
    description = models.CharField(max_length=100)
    type = models.ForeignKey(discount_type, on_delete=models.PROTECT, default="1")
    disc_value = models.DecimalField(max_digits=7, decimal_places=4)
    value_type = models.ForeignKey(discount_number_type, on_delete=models.PROTECT, default="1")
    fromdate = models.DateField(default="1970-01-01")
    todate = models.DateField(default="2099-12-31")

class tkt_money_value(models.Model):
    order = models.ForeignKey(order_tracker, on_delete=models.PROTECT)
    pafdesc = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    value = models.DecimalField(max_digits=7, decimal_places=4)
    site = models.ForeignKey(sites_tracker, on_delete=models.PROTECT)
    contract = models.ForeignKey(contract_tracker, on_delete=models.PROTECT)
    discounted = models.CharField(max_length=1)
    sortorder = models.IntegerField()

class tkt_discount_association(models.Model):
    discount = models.ForeignKey(discount_tracker, on_delete=models.PROTECT)
    tkt = models.ForeignKey(tkt_money_value, on_delete=models.PROTECT)
    calc_order = models.IntegerField()

class kpi_type(models.Model):
    description = models.CharField(max_length=100)

class kpi_tracker(models.Model):
    contract = models.ForeignKey(contract_tracker, on_delete=models.PROTECT)
    order = models.ForeignKey(order_tracker, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    tool = models.CharField(max_length=100)
    kpi_type = models.ForeignKey(kpi_type, on_delete=models.PROTECT, default="2")
    sortorder = models.IntegerField()
    target = models.DecimalField(max_digits=7, decimal_places=4)
    tier1 = models.DecimalField(max_digits=7, decimal_places=4)
    tier2 = models.DecimalField(max_digits=7, decimal_places=4)
    tier3 = models.DecimalField(max_digits=7, decimal_places=4)
    bonustarget = models.DecimalField(max_digits=7, decimal_places=4)
    bonustier1 = models.DecimalField(max_digits=7, decimal_places=4)
    bonustier2 = models.DecimalField(max_digits=7, decimal_places=4)
    bonustier3 = models.DecimalField(max_digits=7, decimal_places=4)
    bonustier4 = models.DecimalField(max_digits=7, decimal_places=4)

class c87_ivr_187(models.Model):
    INTERV_ID = models.IntegerField(primary_key=True, unique=True)
    COD_FISC_P_IVA = models.CharField(max_length=16)
    NUM_TEL = models.CharField(max_length=20)
    POST_SELECTION = models.CharField(max_length=20)
    NOME = models.CharField(max_length=200)
    DATA_INT = models.CharField(max_length=10)
    MACRO_ESIGENZA = models.CharField(max_length=20)
    ORA = models.CharField(max_length=5)
    ASC = models.CharField(max_length=20)
    MODULO = models.CharField(max_length=20)
    SEGMENTO = models.CharField(max_length=20)
    QQ0 = models.IntegerField()
    DD1 = models.IntegerField()
    DD2 = models.IntegerField()
    DD3 = models.IntegerField()
    DD4 = models.IntegerField()
    DD5 = models.IntegerField()
    DD6 = models.IntegerField()
    DD7 = models.IntegerField()
    DD8 = models.IntegerField()
    def __str__(self):
        return self

class c87_ivr_191(models.Model):
    INTERV_ID = models.IntegerField(primary_key=True, unique=True)
    COD_FISC_P_IVA = models.CharField(max_length=16)
    NUM_TEL = models.CharField(max_length=20)
    POST_SELECTION = models.CharField(max_length=20)
    NOME = models.CharField(max_length=200)
    DATA_INT = models.CharField("Data", max_length=10)
    MACRO_ESIGENZA = models.CharField(max_length=20)
    ORA = models.CharField(max_length=5)
    ASC = models.CharField(max_length=20)
    MODULO = models.CharField(max_length=20)
    SEGMENTO = models.CharField(max_length=20)
    QQ0 = models.IntegerField()
    DD1 = models.IntegerField()
    DD2 = models.IntegerField()
    DD3 = models.IntegerField()
    DD4 = models.IntegerField()
    DD5 = models.IntegerField()
    DD6 = models.IntegerField()
    DD7 = models.IntegerField()
    DD8 = models.IntegerField()
    def __str__(self):
        return self

class tools_credentials(models.Model):
    user = models.CharField(max_length=40, unique=True, primary_key=True)
    password = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

class c87_ASC(models.Model):
    ID = models.CharField(max_length=2, unique=True, primary_key=True)
    ASC = models.CharField(max_length=40, unique=True)

class c87_group(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    Keys_ASC = models.ForeignKey(c87_ASC, on_delete=models.PROTECT, default="ND")
    BACINO = models.CharField(max_length=40, unique=True)

class OpeRA_services(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    SERVICE = models.CharField(max_length=20, unique=True)

class c87_ibia_service(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    SERVICE = models.CharField(max_length=40, unique=True)

class c87_ibia_rows(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    ROW = models.CharField(max_length=40, unique=True)

class Paco_services(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    SERVICE = models.CharField(max_length=40, unique=True)

class Paco_MOS_MOI(models.Model):
    ID = models.CharField(max_length=3, unique=True, primary_key=True)
    CENTRO = models.CharField(max_length=20, unique=True)
    TIPO = models.CharField(max_length=3)

class OpeRA_sintesi_volumi_FE_Home(models.Model):
    ID = models.CharField(max_length=10, primary_key=True, unique=True)
    MonthYear = models.CharField(max_length=4)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(OpeRA_services, on_delete=models.PROTECT)
    APERTURE_Totale = models.IntegerField()
    APERTURE_di_cui_BOD = models.IntegerField()
    APERTURE_perc_cui_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    RILAVORAZIONI_Totale = models.IntegerField()
    RILAVORAZIONI_di_cui_BOD = models.IntegerField()
    RILAVORAZIONI_perc_cui_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    FE_CORR_Totale = models.IntegerField()
    FE_CORR_di_cui_da_Apertura = models.IntegerField()
    FE_CORR_di_cui_da_Rilavorazione = models.IntegerField()
    CHIUSURE_FE_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_perc_Ch_Ap = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Aperture_di_cui_BOD = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_perc_Ch_BOD_Ap_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_perc_Ch_ril_Ril = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_di_cui_BOD = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_perc_Ch_ril_BOD_Ril_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_LAV_FE_INCOMPLETE = models.IntegerField()
    SOSPENSIONI_Proposte_di_Ch_FE = models.IntegerField()
    SOSPENSIONI_Proposte_di_2a_lav = models.IntegerField()
    SOSPENSIONI_Proposte_di_Disp = models.IntegerField()
    DISP_DA_FE_Totale = models.IntegerField()
    DISP_DA_FE_di_cui_BOD = models.IntegerField()
    Esito_proposte_per_il_Disp_OK_ADC = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_a_b = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_di_cui_chiusi_a = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_di_cui_disp_b = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_CHIUSI_ADC = models.IntegerField()
    Esito_proposte_per_il_Disp_ALTRO = models.IntegerField()
    Esito_proposte_di_Chiusura_OK_CHIUSI_FE = models.IntegerField()
    Esito_proposte_di_Chiusura_KO_CHIUSI_FE = models.IntegerField()
    Trasf_Diretti_FE_to_BO = models.IntegerField()
    Trasf_Diretti_FE_to_Cteam = models.IntegerField()
    Trasf_Diretti_FE_to_OUT_ASO = models.IntegerField()
    Trasf_Diretti_perc_OCS = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_FE_Totale_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_ONTA = models.IntegerField()
    Esiti_chiusura_On_Field_perc_ONTA = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ON = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ON = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ONT = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ONT = models.DecimalField(max_digits=7, decimal_places=4)


class OpeRA_sintesi_volumi_FE_Office(models.Model):
    ID = models.CharField(max_length=10, primary_key=True, unique=True)
    MonthYear = models.CharField(max_length=4)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(OpeRA_services, on_delete=models.PROTECT)
    APERTURE_Totale = models.IntegerField()
    APERTURE_di_cui_BOD = models.IntegerField()
    APERTURE_perc_cui_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    RILAVORAZIONI_Totale = models.IntegerField()
    RILAVORAZIONI_di_cui_BOD = models.IntegerField()
    RILAVORAZIONI_perc_cui_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    FE_CORR_Totale = models.IntegerField()
    FE_CORR_di_cui_da_Apertura = models.IntegerField()
    FE_CORR_di_cui_da_Rilavorazione = models.IntegerField()
    CHIUSURE_FE_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_perc_Ch_Ap = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Aperture_di_cui_BOD = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Aperture_perc_Ch_BOD_Ap_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_Totale = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_perc_Ch_ril_Ril = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_di_cui_BOD = models.IntegerField()
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_perc_Ch_ril_BOD_Ril_BOD = models.DecimalField(max_digits=7, decimal_places=4)
    CHIUSURE_FE_Di_cui_da_Rilavorazioni_LAV_FE_INCOMPLETE = models.IntegerField()
    SOSPENSIONI_Proposte_di_Ch_FE = models.IntegerField()
    SOSPENSIONI_Proposte_di_2a_lav = models.IntegerField()
    SOSPENSIONI_Proposte_di_Disp = models.IntegerField()
    DISP_DA_FE_Totale = models.IntegerField()
    DISP_DA_FE_di_cui_BOD = models.IntegerField()
    Esito_proposte_per_il_Disp_OK_ADC = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_a_b = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_di_cui_chiusi_a = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_BO_di_cui_disp_b = models.IntegerField()
    Esito_proposte_per_il_Disp_KO_ADC_magg_CHIUSI_ADC = models.IntegerField()
    Esito_proposte_per_il_Disp_ALTRO = models.IntegerField()
    Esito_proposte_di_Chiusura_OK_CHIUSI_FE = models.IntegerField()
    Esito_proposte_di_Chiusura_KO_CHIUSI_FE = models.IntegerField()
    Trasf_Diretti_FE_to_BO = models.IntegerField()
    Trasf_Diretti_FE_to_Cteam = models.IntegerField()
    Trasf_Diretti_FE_to_OUT_ASO = models.IntegerField()
    Trasf_Diretti_perc_OCS = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_FE_Totale_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Totale_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_FE_Totale_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_FE_Di_cui_da_APERTURE_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_Totale_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_N_VER_NEG_Totale = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_N_VER_NEG_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_3gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_3gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_7gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_7gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_30gg = models.IntegerField()
    RIPETUTI_di_cui_BOD_di_cui_da_APERTURE_Ripetuti_30gg_perc = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_ONTA = models.IntegerField()
    Esiti_chiusura_On_Field_perc_ONTA = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ON = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ON = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ONT = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ONT = models.DecimalField(max_digits=7, decimal_places=4)


class OpeRA_sintesi_volumi_BO_Home(models.Model):
    ID = models.CharField(max_length=10, primary_key=True, unique=True)
    MonthYear = models.CharField(max_length=4)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(OpeRA_services, on_delete=models.PROTECT)
    Keys_Totale_Lavorazioni = models.IntegerField()
    Keys_BE_BOM_Chiusure_Totale = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Ver_Neg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_3gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_7gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_30gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_BE_BOM_Sosp_Totale = models.IntegerField()
    BE_BOM_Trasf_BO = models.IntegerField()
    BE_BOM_Trasf_Cteam = models.IntegerField()
    BE_BOM_Trasf_Altro_BO = models.IntegerField()
    BE_BOM_Trasf_OF = models.IntegerField()
    BE_BOM_Trasf_BE_BOM_Correlazioni = models.IntegerField()
    BE_BOM_Trasf_BO_Chiusure_Totale = models.IntegerField()
    BO_Chiusure_RIPETUTI_Ver_Neg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_3gg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_7gg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_30gg = models.IntegerField()
    BO_Trasf_Altro_BO = models.IntegerField()
    BO_Trasf_OF = models.IntegerField()
    BO_Trasf_BO_Correlazioni = models.IntegerField()
    Esiti_chiusura_On_Field_ONTA = models.IntegerField()
    Esiti_chiusura_On_Field_perc_ONTA = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ON = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ON = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ONT = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ONT = models.DecimalField(max_digits=7, decimal_places=4)


class OpeRA_sintesi_volumi_BO_Office(models.Model):
    ID = models.CharField(max_length=10, primary_key=True, unique=True)
    MonthYear = models.CharField(max_length=4)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(OpeRA_services, on_delete=models.PROTECT)
    Keys_Totale_Lavorazioni = models.IntegerField()
    Keys_BE_BOM_Chiusure_Totale = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Ver_Neg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_3gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_7gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_Rip_30gg = models.IntegerField()
    BE_BOM_Chiusure_RIPETUTI_BE_BOM_Sosp_Totale = models.IntegerField()
    BE_BOM_Trasf_BO = models.IntegerField()
    BE_BOM_Trasf_Cteam = models.IntegerField()
    BE_BOM_Trasf_Altro_BO = models.IntegerField()
    BE_BOM_Trasf_OF = models.IntegerField()
    BE_BOM_Trasf_BE_BOM_Correlazioni = models.IntegerField()
    BE_BOM_Trasf_BO_Chiusure_Totale = models.IntegerField()
    BO_Chiusure_RIPETUTI_Ver_Neg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_3gg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_7gg = models.IntegerField()
    BO_Chiusure_RIPETUTI_Rip_30gg = models.IntegerField()
    BO_Trasf_Altro_BO = models.IntegerField()
    BO_Trasf_OF = models.IntegerField()
    BO_Trasf_BO_Correlazioni = models.IntegerField()
    Esiti_chiusura_On_Field_ONTA = models.IntegerField()
    Esiti_chiusura_On_Field_perc_ONTA = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ON = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ON = models.DecimalField(max_digits=7, decimal_places=4)
    Esiti_chiusura_On_Field_di_cui_ONT = models.IntegerField()
    Esiti_chiusura_On_Field_perc_di_cui_ONT = models.DecimalField(max_digits=7, decimal_places=4)


class Paco_richiamate_FE_187(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Data = models.CharField(max_length=10)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(Paco_services, on_delete=models.PROTECT)
    n_chiamate = models.IntegerField()
    Abbattute = models.IntegerField()
    Richiamate_Soglia = models.IntegerField()
    Richiamate_Giorno = models.IntegerField()
    Richiamate_3_Giorni = models.IntegerField()
    Richiamate_nella_settimana = models.IntegerField()


class Paco_richiamate_FE_191(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Data = models.CharField(max_length=10)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(Paco_services, on_delete=models.PROTECT)
    n_chiamate = models.IntegerField()
    Abbattute = models.IntegerField()
    Richiamate_Soglia = models.IntegerField()
    Richiamate_Giorno = models.IntegerField()
    Richiamate_3_Giorni = models.IntegerField()
    Richiamate_nella_settimana = models.IntegerField()


class c87_KPI_KPO_obtained(models.Model):
    ID = models.CharField(max_length=19, primary_key=True, unique=True)
    MonthYear = models.CharField(max_length=4)
    Day = models.DateField()
    FEH_Ivr_Semplici = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Ivr_Medio_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Ivr_Home_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Richiamate_Semplici = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Richiamate_Medio_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Richiamate_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Rework_FONIA_HOME = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Rework_DATI_HOME = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Rework_FIBRA_HOME = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_ONT_Fonia = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_ONT_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_ONT_Fibra = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_BO_Fonia = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_BO_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_BO_Fibra = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_OF_Fonia = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_OF_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    FEH_Invio_OF_Fibra = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Ivr_Medio_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Ivr_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Richiamate_Medio_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Richiamate_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Rework_Medie = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Rework_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_ONT_Medie = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_ONT_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Invio_BO_Medie = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Invio_BO_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Invio_OF_Medie = models.DecimalField(max_digits=7, decimal_places=4)
    FEO_Invio_OF_Complesse = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_REWORK_VN_RIP7GG_FONIA = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_REWORK_VN_RIP7GG_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_REWORK_VN_RIP7GG_FIBRA = models.DecimalField(max_digits=7, decimal_places=4)
    BO_ONT_Fonia = models.DecimalField(max_digits=7, decimal_places=4)
    BO_ONT_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    BO_ONT_Fibra = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_INVIO_OF_FONIA = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_INVIO_OF_ADSL = models.DecimalField(max_digits=7, decimal_places=4)
    BO_BO_INVIO_OF_FIBRA = models.DecimalField(max_digits=7, decimal_places=4)
    BO_C_TEAM_FONIA_DATI = models.DecimalField(max_digits=7, decimal_places=4)
    BO_RIPETIZIONE_A_33_GG_SU_COLLAUDI = models.DecimalField(max_digits=7, decimal_places=4)


class c87_ibia_residential(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Date = models.CharField(max_length=10)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(c87_ibia_service, on_delete=models.PROTECT)
    DIAGNOSI_FE_MACRODES = models.ForeignKey(c87_ibia_rows, on_delete=models.PROTECT)
    Nro_TK = models.IntegerField()
    Verifiche_Negative = models.IntegerField()
    Nro_TK_RIP_1GG = models.IntegerField()


class c87_ibia_business(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Date = models.CharField(max_length=10)
    Keys_BACINO = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    Keys_SERVIZIO = models.ForeignKey(c87_ibia_service, on_delete=models.PROTECT)
    DIAGNOSI_FE_MACRODES = models.ForeignKey(c87_ibia_rows, on_delete=models.PROTECT)
    Nro_TK = models.IntegerField()
    Verifiche_Negative = models.IntegerField()
    Nro_TK_RIP_1GG = models.IntegerField()


class sos_easy_sms_risposte(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Cod_Invio = models.CharField(max_length=100)
    Dettdata_Invio_Sms = models.CharField(max_length=100)
    Ett_Risposte = models.CharField(max_length=100)
    Impianto_Risposte = models.CharField(max_length=100)
    Data_Lavorazione_Bacini_BO = models.CharField(max_length=100)
    Dataconsegna_Sms_Risposte = models.CharField(max_length=100)
    Cod_Risposta = models.CharField(max_length=100)
    Data_Invio_Risposta_Cliente = models.CharField(max_length=100)
    Mittente_Sms_Risposta = models.CharField(max_length=100)
    Data_Ricezione_Sms_Risposta = models.CharField(max_length=100)
    Testo_Sms_Risposta = models.TextField()
    Descr_Accettazione = models.CharField(max_length=100)
    Descr_Invio = models.CharField(max_length=100)
    Codice_Esito = models.CharField(max_length=100)
    Descrizione_Esito = models.CharField(max_length=100)
    Cod = models.CharField(max_length=100)
    Nome = models.CharField(max_length=100)
    Blocco_Notturno = models.CharField(max_length=100)
    DESCR_TEMPLATE = models.CharField(max_length=100)
    BACINO_BOF = models.CharField(max_length=100)
    SMS_Short = models.CharField(max_length=100)
    A = models.CharField(max_length=10)
    M = models.CharField(max_length=10)
    G = models.CharField(max_length=10)
    Chk = models.CharField(max_length=10)
    Tronca_TT = models.CharField(max_length=100)
    BACINO_BO = models.CharField(max_length=100)
    Primo_SMS = models.CharField(max_length=100)
    Esito = models.CharField(max_length=100)


class sos_easy_sms_fake(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    Cod_Template = models.CharField(max_length=100)
    Destinatario = models.CharField(max_length=100)
    Start_Date = models.CharField(max_length=100)
    End_Date = models.CharField(max_length=100)
    Data_Ins = models.CharField(max_length=100)
    Esito_Accettazione = models.CharField(max_length=100)
    Motivo_Ko = models.CharField(max_length=100)
    Data_Invio = models.CharField(max_length=100)
    Esito_Invio = models.CharField(max_length=100)
    Data_Consegna = models.CharField(max_length=100)
    Data_Sr = models.CharField(max_length=100)
    Esito_Sr = models.CharField(max_length=100)
    ETT = models.CharField(max_length=100)
    Tempo_Consegna = models.CharField(max_length=100)
    Dim_Sms_Ingiornata = models.CharField(max_length=100)
    Tempo_Consegnaingiornata = models.CharField(max_length=100)
    Cod_Invio = models.CharField(max_length=100)
    Impianto = models.CharField(max_length=100)
    BACINO_BOF = models.CharField(max_length=100)
    Codice_Esito = models.CharField(max_length=100)
    Descrizione_Esito = models.CharField(max_length=100)
    Descr_Sms_Stessogiorno = models.CharField(max_length=100)
    Descr_Notifica_Sms = models.CharField(max_length=100)
    Cod = models.CharField(max_length=100)
    Nome = models.CharField(max_length=100)
    Mittente = models.CharField(max_length=100)
    Stato_Template = models.CharField(max_length=100)
    Creato_Da = models.CharField(max_length=100)
    Creato_Il = models.CharField(max_length=100)
    Modificato_Da = models.CharField(max_length=100)
    Modificato_Il = models.CharField(max_length=100)
    Priorita = models.CharField(max_length=100)
    Settore = models.CharField(max_length=100)
    Qta_Invii = models.CharField(max_length=100)
    Qta_Sms_OK = models.CharField(max_length=100)
    Qta_Sms_KO = models.CharField(max_length=100)
    Qta_Fake = models.CharField(max_length=100)
    Qta_Kosys = models.CharField(max_length=100)
    TroncaTT = models.CharField(max_length=100)
    A = models.CharField(max_length=10)
    M = models.CharField(max_length=10)
    G = models.CharField(max_length=10)
    BACINO_BO = models.CharField(max_length=100)


class sos_easy_sms_non3xx(models.Model):
    ID = models.CharField(max_length=20, primary_key=True, unique=True)
    PROGRESSIVO = models.CharField(max_length=100)
    DATA_ETT = models.CharField(max_length=100)
    ETT = models.CharField(max_length=100)
    PTT = models.CharField(max_length=100)
    CLIENTELA = models.CharField(max_length=100)
    DESCRIZIONE = models.CharField(max_length=100)
    IMPROPRIO = models.CharField(max_length=100)
    ADDEBITO = models.CharField(max_length=100)
    BACINO = models.CharField(max_length=100)
    AOT = models.CharField(max_length=100)
    NAT = models.CharField(max_length=100)
    SERVIZIO = models.CharField(max_length=100)
    TIPO = models.CharField(max_length=100)
    BACINO_BOF = models.CharField(max_length=100)
    AOT_BO = models.CharField(max_length=100)
    NAT_BO = models.CharField(max_length=100)
    CLI = models.CharField(max_length=100)
    TIPO_LAV = models.CharField(max_length=100)
    MIN_SLA = models.CharField(max_length=100)
    FORNITORE = models.CharField(max_length=100)
    RICAVO = models.CharField(max_length=100)
    CAUSALE_TTMARS = models.CharField(max_length=100)
    PAROLA = models.CharField(max_length=100)
    USCITA_ETTM = models.CharField(max_length=100)
    TIPO_INTERVENTO = models.CharField(max_length=100)
    CF_PIVA = models.CharField(max_length=100)
    RECAPITO_ALTERNATIVO = models.CharField(max_length=100)
    DATA_APP = models.CharField(max_length=100)
    DATA_LAV = models.CharField(max_length=100)
    TIPO_LINEA = models.CharField(max_length=100)
    FLG_SWAP = models.CharField(max_length=100)
    AOA = models.CharField(max_length=100)
    AOL = models.CharField(max_length=100)
    AOU = models.CharField(max_length=100)


class sos_easy_ibia(models.Model):
    ETT = models.CharField(max_length=10, primary_key=True, unique=True)
    PTT = models.CharField(max_length=15)
    CLI = models.CharField(max_length=20)
    CLIENTELA = models.CharField(max_length=10)
    DESCRIZIONE_LAVORAZIONE = models.TextField()
    TIPO_INTERVENTO = models.CharField(max_length=50)
    TIPO_LAVORAZIONE = models.CharField(max_length=50)
    SERVIZIO = models.CharField(max_length=10)
    CODICE_RISCONTRO = models.CharField(max_length=5)
    WR = models.CharField(max_length=10)
    STATO_WR = models.CharField(max_length=10)
    DATA_SEGNALAZIONE = models.CharField(max_length=16)
    DATA_CHIUSURA = models.CharField(max_length=16)
    FATTURATO = models.CharField(max_length=2)
    NULLO = models.CharField(max_length=2)
    IMPROPRIO = models.CharField(max_length=2)
    ASA_INSERIMENTO = models.CharField(max_length=20)
    BACINO_INSERIMENTO = models.CharField(max_length=5)
    SEDE_INSERIMENTO = models.CharField(max_length=20)
    TEAM_INSERIMENTO = models.CharField(max_length=20)
    ASA_LAVORAZIONE = models.CharField(max_length=10)
    BACINO_LAVORAZIONE = models.CharField(max_length=2)
    SEDE_LAVORAZIONE = models.ForeignKey(c87_ASC, on_delete=models.PROTECT, default="ND")
    TEAM_LAVORAZIONE = models.ForeignKey(c87_group, on_delete=models.PROTECT)
    DATA_LAVORAZIONE = models.CharField(max_length=16)
    DATA_TK = models.CharField(max_length=8)
    RICAVO = models.DecimalField(max_digits=7, decimal_places=4)
    MATRICOLA_INSERIMENTO = models.CharField(max_length=20)
    MATRICOLA_LAVORAZIONE = models.CharField(max_length=20)
    TIPO_LINEA = models.CharField(max_length=50)
    DATA_PRESA_IN_CARICO = models.CharField(max_length=16)
    DATA_SOSPENSIONE_ATPAY = models.CharField(max_length=16)
    DATA_ASSEGNAZIONE_ADDETTO = models.CharField(max_length=16)
    TEMPO_SLA_ND_Min = models.IntegerField()
    RECAPITO_ALTERNATIVO = models.CharField(max_length=20)
    ISO_WEEK_DAY = models.CharField(max_length=1)
